Traceback (most recent call last):
  File "create_leave1out.py", line 62, in <module>
    create_ntrue_1false(args.graphpath,args.rdfpath)
  File "create_leave1out.py", line 16, in create_ntrue_1false
    falseclaim_g=nx.read_edgelist(os.path.join(rdf_path,"false_claims","claim{}.edgelist".format(claim_ID)),comments="@")
  File "</N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-584>", line 2, in read_edgelist
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/networkx/utils/decorators.py", line 214, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/home/z/k/zkachwal/Carbonate/factcheckgraph_data/rdf_files/false_claims/claim1.edgelist'

real	7m41.717s
user	7m22.480s
sys	0m0.397s
Traceback (most recent call last):
  File "create_leave1out.py", line 64, in <module>
    create_ntrue_1true(args.graphpath,args.rdfpath)
  File "create_leave1out.py", line 38, in create_ntrue_1true
    trueclaim_g=nx.read_edgelist(os.path.join(rdf_path,"true_claims","claim{}.edgelist".format(claim_ID2)),comments="@")
  File "</N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-584>", line 2, in read_edgelist
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/networkx/utils/decorators.py", line 214, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/home/z/k/zkachwal/Carbonate/factcheckgraph_data/rdf_files/true_claims/claim2003.edgelist'

real	0m13.372s
user	0m4.079s
sys	0m0.245s
