embed
slurmstepd: error: _is_a_lwp: open() /proc/12896/status failed: No such file or directory

real	2m52.523s
user	33m8.401s
sys	0m23.822s

real	0m39.875s
user	8m54.252s
sys	0m7.415s
find_shortest_paths

real	21m43.422s
user	952m33.100s
sys	2m21.997s

real	6m3.202s
user	267m20.056s
sys	1m23.598s

real	0m26.851s
user	0m22.154s
sys	0m1.464s

real	1m10.964s
user	1m2.240s
sys	0m3.943s
plot graphs
plot_sp.py:53: RuntimeWarning: invalid value encountered in double_scalars
  f1scores=[2*(precision[i]*recall[i])/(precision[i]+recall[i]) for i in range(len(thresholds))]
plot_sp.py:53: RuntimeWarning: invalid value encountered in double_scalars
  f1scores=[2*(precision[i]*recall[i])/(precision[i]+recall[i]) for i in range(len(thresholds))]

real	0m9.567s
user	0m6.837s
sys	0m1.293s

real	0m11.220s
user	0m8.510s
sys	0m1.317s
plot_sp.py:53: RuntimeWarning: invalid value encountered in double_scalars
  f1scores=[2*(precision[i]*recall[i])/(precision[i]+recall[i]) for i in range(len(thresholds))]
plot_sp.py:53: RuntimeWarning: invalid value encountered in double_scalars
  f1scores=[2*(precision[i]*recall[i])/(precision[i]+recall[i]) for i in range(len(thresholds))]
plot_sp.py:53: RuntimeWarning: invalid value encountered in double_scalars
  f1scores=[2*(precision[i]*recall[i])/(precision[i]+recall[i]) for i in range(len(thresholds))]
plot_sp.py:53: RuntimeWarning: invalid value encountered in double_scalars
  f1scores=[2*(precision[i]*recall[i])/(precision[i]+recall[i]) for i in range(len(thresholds))]

real	0m18.245s
user	0m14.330s
sys	0m2.551s

real	0m20.183s
user	0m16.058s
sys	0m2.748s
