Traceback (most recent call last):
  File "find_adj_pairs.py", line 51, in <module>
    find_adj_pairs2(args.graphpath,args.fcgclass,args.kgtype)
  File "find_adj_pairs.py", line 30, in find_adj_pairs2
    intersect_all_pairs=np.load(intersect_path+"_all_entityPairs_{}_{}.npy".format(kg_label,fcg_class))
  File "/N/u/zkachwal/Carbonate/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/home/z/k/zkachwal/BigRed3/factcheckgraph_data/graphs/fred1/intersect_all_entityPairs_dbpedia_fred1.npy'

real	22m56.591s
user	22m29.308s
sys	0m18.476s
slurmstepd: error: *** JOB 52042 ON nid00353 CANCELLED AT 2019-11-17T01:46:35 DUE TO TIME LIMIT ***
