Traceback (most recent call last):
  File "experiment2.py", line 64, in <module>
    uris_dict,edgelist=parse_dbpedia()
  File "experiment2.py", line 5, in parse_dbpedia
    g.parse(os.path.join('gpfs','home','z','k','zkachwal','Carbonate','DBPedia Data','dbpedia_graph.nt'),format='nt')
NameError: name 'os' is not defined

real	0m6.186s
user	0m0.320s
sys	0m0.141s
