Traceback (most recent call last):
  File "calculate_stats.py", line 71, in <module>
    calculate_stats(args.graphpath,args.graphclass,args.graphtype)
  File "calculate_stats.py", line 15, in calculate_stats
    graph_stats=pd.DataFrame(index=stats_index,columns=g_labels)
NameError: name 'g_labels' is not defined

real	1m18.585s
user	0m1.647s
sys	0m0.945s
Traceback (most recent call last):
  File "calculate_stats.py", line 71, in <module>
    calculate_stats(args.graphpath,args.graphclass,args.graphtype)
  File "calculate_stats.py", line 15, in calculate_stats
    graph_stats=pd.DataFrame(index=stats_index,columns=g_labels)
NameError: name 'g_labels' is not defined

real	0m2.413s
user	0m0.923s
sys	0m0.405s
Traceback (most recent call last):
  File "calculate_stats.py", line 71, in <module>
    calculate_stats(args.graphpath,args.graphclass,args.graphtype)
  File "calculate_stats.py", line 15, in calculate_stats
    graph_stats=pd.DataFrame(index=stats_index,columns=g_labels)
NameError: name 'g_labels' is not defined

real	0m1.096s
user	0m0.761s
sys	0m0.281s
Traceback (most recent call last):
  File "calculate_stats.py", line 71, in <module>
    calculate_stats(args.graphpath,args.graphclass,args.graphtype)
  File "calculate_stats.py", line 15, in calculate_stats
    graph_stats=pd.DataFrame(index=stats_index,columns=g_labels)
NameError: name 'g_labels' is not defined

real	0m1.074s
user	0m0.741s
sys	0m0.285s
Traceback (most recent call last):
  File "calculate_stats.py", line 71, in <module>
    calculate_stats(args.graphpath,args.graphclass,args.graphtype)
  File "calculate_stats.py", line 15, in calculate_stats
    graph_stats=pd.DataFrame(index=stats_index,columns=g_labels)
NameError: name 'g_labels' is not defined

real	0m1.090s
user	0m0.764s
sys	0m0.272s
Traceback (most recent call last):
  File "calculate_stats.py", line 71, in <module>
    calculate_stats(args.graphpath,args.graphclass,args.graphtype)
  File "calculate_stats.py", line 15, in calculate_stats
    graph_stats=pd.DataFrame(index=stats_index,columns=g_labels)
NameError: name 'g_labels' is not defined

real	0m1.074s
user	0m0.749s
sys	0m0.276s
Traceback (most recent call last):
  File "calculate_stats.py", line 71, in <module>
    calculate_stats(args.graphpath,args.graphclass,args.graphtype)
  File "calculate_stats.py", line 15, in calculate_stats
    graph_stats=pd.DataFrame(index=stats_index,columns=g_labels)
NameError: name 'g_labels' is not defined

real	0m1.067s
user	0m0.735s
sys	0m0.282s
Traceback (most recent call last):
  File "calculate_stats.py", line 71, in <module>
    calculate_stats(args.graphpath,args.graphclass,args.graphtype)
  File "calculate_stats.py", line 15, in calculate_stats
    graph_stats=pd.DataFrame(index=stats_index,columns=g_labels)
NameError: name 'g_labels' is not defined

real	0m1.055s
user	0m0.723s
sys	0m0.286s
Traceback (most recent call last):
  File "calculate_stats.py", line 71, in <module>
    calculate_stats(args.graphpath,args.graphclass,args.graphtype)
  File "calculate_stats.py", line 15, in calculate_stats
    graph_stats=pd.DataFrame(index=stats_index,columns=g_labels)
NameError: name 'g_labels' is not defined

real	0m1.106s
user	0m0.751s
sys	0m0.298s
Traceback (most recent call last):
  File "calculate_stats.py", line 71, in <module>
    calculate_stats(args.graphpath,args.graphclass,args.graphtype)
  File "calculate_stats.py", line 15, in calculate_stats
    graph_stats=pd.DataFrame(index=stats_index,columns=g_labels)
NameError: name 'g_labels' is not defined

real	0m1.086s
user	0m0.762s
sys	0m0.276s
Traceback (most recent call last):
  File "calculate_stats.py", line 71, in <module>
    calculate_stats(args.graphpath,args.graphclass,args.graphtype)
  File "calculate_stats.py", line 15, in calculate_stats
    graph_stats=pd.DataFrame(index=stats_index,columns=g_labels)
NameError: name 'g_labels' is not defined

real	0m1.083s
user	0m0.740s
sys	0m0.292s
Traceback (most recent call last):
  File "calculate_stats.py", line 71, in <module>
    calculate_stats(args.graphpath,args.graphclass,args.graphtype)
  File "calculate_stats.py", line 15, in calculate_stats
    graph_stats=pd.DataFrame(index=stats_index,columns=g_labels)
NameError: name 'g_labels' is not defined

real	0m1.094s
user	0m0.766s
sys	0m0.279s
usage: calculate_stats.py [-h] [-gp graph path] [-gc graph class]
                          [-gt graph type]
calculate_stats.py: error: argument -gc/--graphclass: invalid choice: 'largest_ccf' (choose from 'fred', 'co-occur', 'backbone_df', 'backbone_dc', 'largest_cc', 'kg')

real	0m1.093s
user	0m0.739s
sys	0m0.306s
usage: calculate_stats.py [-h] [-gp graph path] [-gc graph class]
                          [-gt graph type]
calculate_stats.py: error: argument -gc/--graphclass: invalid choice: 'largest_ccf' (choose from 'fred', 'co-occur', 'backbone_df', 'backbone_dc', 'largest_cc', 'kg')

real	0m1.104s
user	0m0.788s
sys	0m0.265s
usage: calculate_stats.py [-h] [-gp graph path] [-gc graph class]
                          [-gt graph type]
calculate_stats.py: error: argument -gc/--graphclass: invalid choice: 'largest_ccf' (choose from 'fred', 'co-occur', 'backbone_df', 'backbone_dc', 'largest_cc', 'kg')

real	0m1.074s
user	0m0.746s
sys	0m0.278s
usage: calculate_stats.py [-h] [-gp graph path] [-gc graph class]
                          [-gt graph type]
calculate_stats.py: error: argument -gc/--graphclass: invalid choice: 'largest_ccc' (choose from 'fred', 'co-occur', 'backbone_df', 'backbone_dc', 'largest_cc', 'kg')

real	0m1.074s
user	0m0.745s
sys	0m0.279s
usage: calculate_stats.py [-h] [-gp graph path] [-gc graph class]
                          [-gt graph type]
calculate_stats.py: error: argument -gc/--graphclass: invalid choice: 'largest_ccc' (choose from 'fred', 'co-occur', 'backbone_df', 'backbone_dc', 'largest_cc', 'kg')

real	0m1.062s
user	0m0.728s
sys	0m0.279s
usage: calculate_stats.py [-h] [-gp graph path] [-gc graph class]
                          [-gt graph type]
calculate_stats.py: error: argument -gc/--graphclass: invalid choice: 'largest_ccc' (choose from 'fred', 'co-occur', 'backbone_df', 'backbone_dc', 'largest_cc', 'kg')

real	0m1.045s
user	0m0.719s
sys	0m0.274s
